usb: phytium: Add support for Phytium USB controller
deepin-community/kernel pull request #140
Opened 2024-05-14 03:20 UTC by wangzhimin1179

This patch adds the Phytium USBHS DRD controller support.  a e2000 can Simulate a USB storage device ,and so on。

2024-05-19 03:39 UTC, Avenger-285714 requested changes

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/dma.c
> +			goto retransmit;
检查goto retransmit，建议换写法，尽量不要横跨if去goto

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/Kconfig
> +	tristate "PHYTIUM USB Support"
建议和飞腾其它驱动配置项保持一致，PHYTIUM改为Phytium

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/dma.c
> +
多了行空行嘛

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/dma.h
> +//#include "list.h"
这行注释的意义是？

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/dma.h
> +#define TD_SING_MAX_TD_DATA_SIZE 65536u
这一段4个define没有对齐

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/gadget.c
> +	//endpoint operation
按照本结构体内下面的风格，是否应该添加空行或在下面删除空行，以及首字母大小写风格是否应该统一

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/host.c
> +//#include "list.h"
这行注释的意义是？

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/host.c
> +	//		if (usbEpPriv->type == USB_ENDPOINT_XFER_INT)
这行注释的意义是？

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/host.c
> +
多了行空行嘛

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/host.c
> +//	struct HW_Regs *regs = priv->regs;
这行注释的意义是？

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/host_api.h
> +//#include "list.h"
这行注释的意义是？

2024-05-19 03:39 UTC, Avenger-285714 commented on drivers/usb/phytium/platform.c
> +//#include <linux/usb/hcd.h>
这行注释的意义是？

2024-05-21 03:09 UTC, wangzhimin1179 commented
先close掉。

2024-05-21 03:09 UTC, closed without merging