Phytium PWM support
deepin-community/kernel pull request #148
Opened 2024-05-15 08:06 UTC by xuyan213

Generic PWM framework driver for the PWM controller found on Phytium SoCs.

2024-05-17 02:35 UTC, Avenger-285714 commented on drivers/pwm/pwm-phytium.c
> +static int pwm_phytium_probe(struct platform_device *pdev)
少了个空行嘛

2024-05-17 02:35 UTC, Avenger-285714 commented on drivers/pwm/sysfs.c
> +	dev_set_name(&export->child, "pwm%u", pwm->pwm);
这里为什么要改？

2024-06-19 08:32 UTC, opsiff requested changes

2024-06-19 08:32 UTC, opsiff commented on drivers/pwm/sysfs.c
> +	dev_set_name(&export->child, "pwm%u", pwm->pwm);
这里用CONFIG_ARCH_PHYTIUM宏控制编译实质上会在arm架构上全部使用dev_set_name(&export->child, "pwm%u", pwm->pwm); 此处应该额外在宏控制前提下加read_cpuid_implementor() == ARM_CPU_IMP_PHYTIUM来在ARM上判断飞腾impl吧

2024-06-27 15:43 UTC, opsiff commented
在 X86 上编译错误 ，之前的ARM架构宏还需要保留
drivers/pwm/sysfs.c: In function ‘pwm_export_child’:
drivers/pwm/sysfs.c:264:13: error: implicit declaration of function ‘read_cpuid_implementor’ [-Werror=implicit-function-declaration]
  264 |         if (read_cpuid_implementor() == ARM_CPU_IMP_PHYTIUM)
      |             ^~~~~~~~~~~~~~~~~~~~~~
drivers/pwm/sysfs.c:264:41: error: ‘ARM_CPU_IMP_PHYTIUM’ undeclared (first use in this function)
  264 |         if (read_cpuid_implementor() == ARM_CPU_IMP_PHYTIUM)
      |                                         ^~~~~~~~~~~~~~~~~~~
drivers/pwm/sysfs.c:264:41: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors

2024-07-01 03:25 UTC, opsiff commented
/ok-to-test

2024-07-01 03:26 UTC, opsiff commented
剩余审查意见: read_cpuid_implementor方法在一个cpu中不同core有除了飞腾implementor时有其他implementor时可能失效，当前暂时无此种情况。

2024-07-01 03:26 UTC, merged