irqchip/gic-phytium-2500: Add support for GIC of  Phytium PS20064
deepin-community/kernel pull request #158
Opened 2024-05-20 02:09 UTC by lyt31

Phytium Ps20064 adjusts the GIC's implementation to support multi-socket
system designs. This patch adds the driver of this new implementation
while keeping the kernel binary compatible with other ARM servers in
the ecosystem.

When system resume from suspend to ram, firmware just restore
GICR_CTLR_ENABLE_LPIs of boot CPU, the other CPUs also should
be restored.

2024-06-19 08:17 UTC, opsiff requested changes

2024-06-19 08:17 UTC, opsiff commented on drivers/irqchip/irq-gic-v3-its.c
> +
这个代码是已经上游了还是只会在飞腾上面生效?

2024-06-19 08:46 UTC, lyt31 commented on drivers/irqchip/irq-gic-v3-its.c
> +
只在飞腾上面生效

2024-06-25 09:10 UTC, opsiff commented
/ok-to-test

2024-06-25 10:14 UTC, merged