hda: phytium: Add Phytium hda driver support
deepin-community/kernel pull request #187
Opened 2024-05-22 10:24 UTC by tianwei08222

This patch adds the Phytium hda driver support.

2024-05-24 10:21 UTC, Avenger-285714 requested changes

2024-05-24 10:21 UTC, Avenger-285714 commented on include/sound/hdaudio.h
> +	bool cmd_resend;		/* command resend */
是否使用:1

2024-05-24 10:21 UTC, Avenger-285714 commented on sound/hda/hdac_controller.c
> +	if (bus->cmd_resend) {
带锁循环？锁粒度太大需要整改

2024-06-27 09:37 UTC, tianwei08222 commented on include/sound/hdaudio.h
> +	bool cmd_resend;		/* command resend */
可以不这样，因为在azx_first_init会赋值成1

2024-06-28 03:18 UTC, tianwei08222 commented on sound/hda/hdac_controller.c
> +	if (bus->cmd_resend) {
补丁部分只有释放锁的，此处修改后也会统一释放（spin_unlock_irq(&bus->reg_lock);），不影响的

2024-07-06 03:03 UTC, Icenowy commented on include/sound/hdaudio.h
> +	bool cmd_resend;		/* command resend */
> 可以不这样，因为在azx_first_init会赋值成1

这里的 :1 不是初始值，而是位域占用空间大小， :1 的话编译器可以看情况压缩成和其他 bool 在同一个字节里，节约内存

2024-07-07 19:06 UTC, Avenger-285714 commented
这个pr有合并冲突，先关闭了。我这边给这个补丁推送了新的提交，请各位同学们review

https://github.com/deepin-community/kernel/pull/312

2024-07-07 19:06 UTC, closed without merging