mtd: rawnand: Add Phytium NAND flash controller support
deepin-community/kernel pull request #199
Opened 2024-05-23 10:13 UTC by studyhu

This patch implements a device driver of NAND flash controller for both Phytium PCIe chipset and SoCs. Since interrupt flags depends on the bus implementation, e.g., PCI vs platform, we extract the interrupt register function from NFC driver core.

2024-05-24 08:53 UTC, opsiff commented
/ok-to-test

2024-05-24 09:15 UTC, Avenger-285714 requested changes

2024-05-24 09:15 UTC, Avenger-285714 commented on drivers/mtd/nand/raw/phytium_nand.c
> +			(u8 *)nfc_op, PHYTIUM_NFC_DSP_SIZE);
建议判断一下cmd_num有没有可能导致越界，下同

2024-05-24 09:15 UTC, Avenger-285714 commented on drivers/mtd/nand/raw/phytium_nand.c
> +				 struct nand_ecc_ctrl *ecc)
代码对齐

2024-05-24 09:15 UTC, Avenger-285714 commented on drivers/mtd/nand/raw/phytium_nand.c
> +		return ret;
kfree(nfc_op);

2024-05-24 09:15 UTC, Avenger-285714 commented on drivers/mtd/nand/raw/phytium_nand.c
> +	nfc_op = kzalloc(2 * sizeof(struct phytium_nfc_op), GFP_KERNEL);
nfc_op没释放

2024-05-24 09:15 UTC, Avenger-285714 commented on drivers/mtd/nand/raw/phytium_nand.c
> +
空行太多

2024-05-28 03:20 UTC, studyhu commented on drivers/mtd/nand/raw/phytium_nand.c
> +			(u8 *)nfc_op, PHYTIUM_NFC_DSP_SIZE);
在phytium_nfc_init_dma函数中，给nfc->dsp_addr 申请PAGE_SIZE的内存大小，然后调用phytium_nfc_send_cmd2函数时，传入的参数cmd_num都是2，PAGE_SIZE要大于i*PHYTIUM_NFC_DSP_SIZE，不会越界。

2024-05-28 03:20 UTC, studyhu commented on drivers/mtd/nand/raw/phytium_nand.c
> +		return ret;
已修改

2024-05-28 03:22 UTC, studyhu commented on drivers/mtd/nand/raw/phytium_nand.c
> +	nfc_op = kzalloc(2 * sizeof(struct phytium_nfc_op), GFP_KERNEL);
已修改

2024-05-28 03:29 UTC, merged