[linux-6.6.y] Add support for Zhaoxin Processors
deepin-community/kernel pull request #253
Opened 2024-06-12 06:55 UTC by leoliu-oc

Let Linux supports new Zhaoxin CPU features and " Shanghai " CPU vendor ID;
let related drivers supports new Zhaoxin CPU FMS.
Fix a CPU topo limitation of Installed kernel use CPUID B leaf to get CPU topo as default,
add 4leaf get CPU cacheinfo additionally.

Note：
Support for the Zhaoxin processor includes two vendor IDs, zhaoxin and centaur, so we will synchronously modify centaur.c and zhaoxin.c.

Include:

1. x86/cpufeatures: Add Zhaoxin feature bits
2. x86/cpu: Add detect extended topology for Zhaoxin CPUs

2024-06-12 07:14 UTC, opsiff commented on arch/x86/include/asm/cpufeatures.h
> +#define X86_FEATURE_CCS        (5*32+4) /*  "sm3 sm4" present */
建议这里和后面没对齐的地方修改缩进和上下文保持一致

2024-06-12 08:16 UTC, opsiff commented
/ok-to-test

2024-06-19 08:38 UTC, opsiff requested changes

2024-06-19 08:38 UTC, opsiff commented on arch/x86/include/asm/cpufeatures.h
> +#define X86_FEATURE_CCS			(5*32+4) /*  "sm3 sm4" present */
这个(5*32+4)相比( 5*32+ 3) 格式不对。下面也需要改。

2024-07-03 02:48 UTC, leoliu-oc commented on arch/x86/include/asm/cpufeatures.h
> +#define X86_FEATURE_CCS			(5*32+4) /*  "sm3 sm4" present */
未与文档既定格式保持一致的原因，是因为会导致checkpatch.pl脚本检查不通过。不过，这边会按照建议修改。

2024-07-03 05:38 UTC, opsiff approved these changes

2024-07-03 05:38 UTC, opsiff commented
/lgtm

2024-07-03 05:38 UTC, merged