Add support for Zhaoxin HW Random Number Generator
deepin-community/kernel pull request #257
Opened 2024-06-12 09:11 UTC by leoliu-oc

zhaoxin inclusion
category: feature

-------------------

This driver provides kernel-side support for the Random Number Generator hardware found on Zhaoxin based motherboards.

2024-06-19 08:50 UTC, opsiff commented on drivers/char/hw_random/via-rng.c
> +		pr_err(PFX "RNG registering failed (%d)\n", err);
这里为什么要修改

2024-06-19 08:52 UTC, opsiff requested changes

2024-06-19 08:52 UTC, opsiff commented on drivers/char/hw_random/zhaoxin-rng.c
> +		pr_err(PFX "The CPU isn't support XSTORE.\n");
这个pr_err要修改成pr_info吧

2024-07-03 03:08 UTC, leoliu-oc commented on drivers/char/hw_random/via-rng.c
> +		pr_err(PFX "RNG registering failed (%d)\n", err);
这里修改的原因是，checkpatch.pl会提示格式warning。不过，这边会恢复保留原先格式。

2024-07-03 03:14 UTC, leoliu-oc commented on drivers/char/hw_random/zhaoxin-rng.c
> +		pr_err(PFX "The CPU isn't support XSTORE.\n");
这里是参考同内核类似情况采用pr_err的。这边的理解是，要么使用pr_err，要么直接不打印任何信息。而改为pr_info的话，会导致在其他非zhaoxin_rng_cpu_ids列表中的处理器平台上会多出冗余打印信息。

2024-07-03 05:39 UTC, opsiff commented
/lgtm

2024-07-03 05:39 UTC, opsiff commented
/ok-to-test

2024-07-03 05:39 UTC, merged