[linux-6.6.y] Driver for Zhaoxin SM3 SM4 algorithms
deepin-community/kernel pull request #272
Opened 2024-06-14 02:24 UTC by leoliu-oc

Includes:
1. Add support for Zhaoxin GMI SM3 Secure Hash algorithm
This SM3 algorithm driver is developed to support the SM3 instruction,
making user develop their applications with both high performance and high
security.
2. Add support for Zhaoxin GMI SM4 Block Cipher algorithm
This SM4 algorithm driver is developed to support the SM4 instruction,
making user develop their applications with both high performance and high
security.

2024-06-19 09:26 UTC, opsiff requested changes

2024-06-19 09:26 UTC, opsiff commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +	pr_warn("GMI is unavailable on this platform.");
这里应该是pr_info 不应该是pr_warn吧 所有x86都会走

2024-06-19 09:26 UTC, opsiff commented on arch/x86/crypto/sm4_zhaoxin_gmi.c
> +		pr_notice("GMI SM4 is available\n");
is available 为什么要用pr_notice?

2024-06-19 09:26 UTC, opsiff commented on arch/x86/crypto/sm4_zhaoxin_gmi.c
> +			pr_notice("GMI SM4 is detected by CPUID\n");
is available 为什么要用pr_notice?

2024-06-19 09:26 UTC, opsiff commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +			pr_notice("GMI SM3 detected by CPUID\n");
is available 为什么要用pr_notice?

2024-06-19 09:26 UTC, opsiff commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +		pr_notice("GMI SM3 is available\n");
is available 为什么要用pr_notice?

2024-07-04 03:24 UTC, leoliu-oc commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +	pr_warn("GMI is unavailable on this platform.");
更新了一般，这里调整了逻辑。在匹配成功后才会pr_info打印。匹配不成功时不打印。这样就只有在兆芯平台才会有打印信息。

2024-07-04 03:25 UTC, leoliu-oc commented on arch/x86/crypto/sm4_zhaoxin_gmi.c
> +		pr_notice("GMI SM4 is available\n");
新版本中改为了pr_debug，供debug时判定用。正常情况下不输出log。

2024-07-04 03:25 UTC, leoliu-oc commented on arch/x86/crypto/sm4_zhaoxin_gmi.c
> +			pr_notice("GMI SM4 is detected by CPUID\n");
同上。

2024-07-04 03:26 UTC, leoliu-oc commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +			pr_notice("GMI SM3 detected by CPUID\n");
同上。

2024-07-04 03:26 UTC, leoliu-oc commented on arch/x86/crypto/sm3_zhaoxin_gmi.c
> +		pr_notice("GMI SM3 is available\n");
同上。

2024-07-04 05:17 UTC, opsiff commented
/lgtm

2024-07-04 05:17 UTC, opsiff commented
/ok-to-test

2024-07-04 05:18 UTC, merged