[linux-6.6.y] ata: ahci: Add support for AHCI SGPIO Enclosure Management
deepin-community/kernel pull request #277
Opened 2024-06-14 10:56 UTC by leoliu-oc

zhaoxin inclusion
category: feature

-------------------

To monitor and control auxiliary service in a drive enclosure, Zhaoxin AHCI controller adds enclosure management support in SGPIO protocols with two messages types:
LED message type and SGPIO register interface message type.

The LED message type uses a genernal ahci specific interface which has already been supported by default ahci driver, the SGPIO register interface message type based on SFF-8485 which defined by vendor specific, this patch adds support for it.

2024-06-19 09:37 UTC, opsiff requested changes

2024-06-19 09:37 UTC, opsiff commented on drivers/ata/Kconfig
> +	default y
default y的话 非X86平台也需要这个么?

2024-07-04 03:46 UTC, leoliu-oc commented on drivers/ata/Kconfig
> +	default y
这边在新版本中添加了对CPU_SUP_ZHAOXIN/CPU_SUP_CENTAUR的依赖。这样就只会在兆芯平台上builtin了。

2024-07-04 04:20 UTC, opsiff commented on drivers/ata/ahci_zhaoxin_sgpio.c
> +		pdev_next = pci_get_device(PCI_VENDOR_ID_ZHAOXIN, 0x9083, pdev_cur);
这种用法没见过，我的理解是PCI上没有这个设备就不注册

2024-07-04 04:22 UTC, opsiff commented
/ok-to-test

2024-07-04 04:22 UTC, merged