[linux-6.6.y] i2c: smbus: Add support for Zhaoxin SMBUS controller
deepin-community/kernel pull request #278
Opened 2024-06-14 11:50 UTC by leoliu-oc

zhaoxin inclusion
category: feature

-------------------

The Zhaoxin platform implements the SMBUS controller on the hardware, enabling information exchange and collaboration between devices using the SMBus protocol.

2024-06-19 09:38 UTC, opsiff requested changes

2024-06-19 09:38 UTC, opsiff commented on drivers/i2c/busses/Kconfig
> +	default m
非X86的话也需要 default m么?

2024-07-04 06:28 UTC, leoliu-oc commented on drivers/i2c/busses/Kconfig
> +	default m
新版中添加了对CPU_SUP_CENTAUR/CPU_SUP_ZHAOXIN的依赖。以保证只有在兆芯平台上，才会编译为module。

2024-07-04 08:59 UTC, opsiff commented
/ok-to-test

2024-07-04 08:59 UTC, merged